jobs:
- job: ${{ parameters.name }}
  pool: ${{ parameters.pool }}
  steps:
  - script: cmake -H. -BBuild
    displayName: 'Configure build'

  - script: cmake --build Build
    displayName: 'Build tests'

  - script: |
      cd Build
      set CTEST_OUTPUT_ON_FAILURE=1
      ctest -j 4 -C Debug
    displayName: 'Run tests'

- job: ${{ parameters.name }}_Static
  pool: ${{ parameters.pool }}
  steps:
  - script: cmake -H. -BBuild -DMINISAT_MSVC_STATIC=ON
    displayName: 'Configure build'

  - script: cmake --build Build
    displayName: 'Build tests'

  - script: |
      cd Build
      set CTEST_OUTPUT_ON_FAILURE=1
      ctest -j 4 -C Debug
    displayName: 'Run tests'

- job: ${{ parameters.name }}_Static_Release
  pool: ${{ parameters.pool }}
  steps:
  - script: cmake -H. -BBuild -DMINISAT_MSVC_STATIC=ON
    displayName: 'Configure build'

  - script: cmake --build Build
    displayName: 'Build tests'

  - script: |
      cd Build
      set CTEST_OUTPUT_ON_FAILURE=1
      ctest -j 4 -C Debug
    displayName: 'Run tests'
